// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTyva9uvpVMz26b9Oocf4nBgj4Lru4mo',
    appId: '1:503823972995:web:424ef6f5c0c16e9f1b79b6',
    messagingSenderId: '503823972995',
    projectId: 'delina-music-network',
    authDomain: 'delina-music-network.firebaseapp.com',
    storageBucket: 'delina-music-network.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbtKuOM5lCGrif4_doitMcgMINk-pVFM',
    appId: '1:503823972995:android:e4cfb6e43db21fd21b79b6',
    messagingSenderId: '503823972995',
    projectId: 'delina-music-network',
    storageBucket: 'delina-music-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKn2IzCr8coyc28lYnY7MRJ8ElFRtSOW4',
    appId: '1:503823972995:ios:4c82e78ac3b26d3c1b79b6',
    messagingSenderId: '503823972995',
    projectId: 'delina-music-network',
    storageBucket: 'delina-music-network.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKn2IzCr8coyc28lYnY7MRJ8ElFRtSOW4',
    appId: '1:503823972995:ios:53754ddc18851cf01b79b6',
    messagingSenderId: '503823972995',
    projectId: 'delina-music-network',
    storageBucket: 'delina-music-network.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
